### ISSUE TITLE
Fix e2e test: gang scheduling.

### ISSUE THREAD

**Issue by TommyLike** [kubernetes-retired/kube-batch#835] opened 2019-04-28 03:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After the revert of batch job patches #806 , the [gang scheduling](https://github.com/kubernetes-sigs/kube-batch/blob/5e9977d68a13938fbb6d7dda564da0dca1b1c98c/test/e2e/job.go#L83) testcase is falling, need investigate and fix.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment] 2019-04-29 13:22
@thandayuthapani , please help to check what happened :)

**Comment by thandayuthapani** [comment] 2019-05-03 03:59
@k82cn It is passing in my local test setup

**Comment by thandayuthapani** [comment] 2019-05-03 04:55
I'm able to find PodGroup Unschedulable event in local test setup, but in Travis is getting timeout at this step because it is not able to find that event or event not getting generated. Will check what is the problem.

**Comment by k82cn** [comment] 2019-05-07 03:00
@thandayuthapani , we found similar issue in [Volcano](http://github.com/volcano-sh/volcano) which because of some change in e2e, refer to https://github.com/volcano-sh/volcano/commit/c53779db2d9547286a6f7d7cec4e8d386855c06c#diff-8349006db2c242fd7424e1dfb3295840R430 for more detail.

**Comment by thandayuthapani** [comment] 2019-05-07 05:27
@k82cn Test Case failure is because of Unschedulable event is not generated so it is getting timed out waiting for unschedulable event and test case fails.  Event is not generated because of fields in  podGroupStatus in PodGroup object is reset to its nil value, while status updater function is called. 
![export1](https://user-images.githubusercontent.com/34565833/57273650-38c05b80-70b6-11e9-906f-29f1a3479942.png)
Since object from API server is then assigned to our local cache object, local cache also looses status information.  Unschedulable event get generated only when the phase of podGroup is pending or Unknown.
![export](https://user-images.githubusercontent.com/34565833/57273620-1d555080-70b6-11e9-8b37-ee52a1c97df6.png)
Attaching the logs of kube-batch, for better understanding.  Status of podGroup is being determined in kube-batch and to update the status, status updater is called and the object returned is assigned back to cache.  Returning object does not have status data.  So it is getting missed.
![export (1)](https://user-images.githubusercontent.com/34565833/57273739-9359b780-70b6-11e9-8612-84af0fa634fb.png)

StatusUpdater uses K8s Update API call, when that is being replaced with UpdateStatus call, test case passed.  Some problem with Update call, where status data is getting reset to its nil value.

**Comment by k82cn** [comment] 2019-05-07 06:08
> StatusUpdater uses K8s Update API call, when that is being replaced with UpdateStatus call, test case passed. 

Can you help to check history why it's failed recently?

**Comment by thandayuthapani** [comment] 2019-05-07 06:15
It used to pass with local DINDv1.13 setup, but once I Cleaned that setup and brought up new setup of DIND-v1.13, I started facing the same problem as CI was facing. I think after DIND pulls new images for kubernetes components, it is facing this problem.  Because it was not facing the problem in my old DIND setup with same code, but with new DIND setup(New images being pulled for kubernetes components), it was facing the issue, with no change in code.  There was no change in DIND version, but only new images were being pulled by DIND clusters for kubernetes components.

**Comment by k82cn** [comment] 2019-05-07 07:08
but volcano-sh/kube-batch seems fine without this fix.

**Comment by thandayuthapani** [comment] 2019-05-07 07:13
That test case has been skipped in volcano/kube-batch

**Comment by k82cn** [comment] 2019-05-07 07:20
xref https://travis-ci.com/volcano-sh/volcano/jobs/198124601 , it has been fixed in the commit that I mentioned above.

**Comment by thandayuthapani** [comment] 2019-05-07 08:01
It volcano-sh/volcano we are using KIND to bring k8s cluster, but in kubernetes-sigs/kube-batch we use DIND to bring us k8s cluster.

**Comment by k82cn** [comment] 2019-05-07 08:10
then try kind; honestly, I'm unconfotable about the fix if we do not know the root cause :)

**Comment by thandayuthapani** [comment] 2019-05-07 09:37
With Local KIND setup, gang scheduling and statement test case is passing, should I have to make change in Kube-Batch to use KIND now in CI?

**Comment by k82cn** [comment] 2019-05-07 12:04
ok, let's try kind :)

**Closed as completed** 2019-05-15 06:00 UTC
Labels: kind/bug
