### ISSUE TITLE
Support gang scheduling (hard) for podset

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes-retired/kube-batch#158] opened 2018-02-06 08:38 UTC
When resources are not sufficient, `kube-batchd` just tries to start `minAvailable` pods of each application as much as possible. It will cause the running pods' size of a podSet is less than `minAvailable` which is not acceptable for some applications, e.g. MPI.

To handle above issue, `kube-batchd` need to support that it will not assign any resources to the job unless its `minAvailable` could be met.

**Comment by wojciechwasko** [comment] 2018-02-06 09:02
I believe the issue is only partly in the gang scheduling (MPI could work around that with "slave" pods just squatting on the resources until master connects to them and scheduling the master pod _last_).

To refine the problem, the crux of the issue is preventing deadlocks. If two users run two large jobs (each occupying >half of available nodes) at the same time, I we can easily run into a deadlock (the larger the job, the higher the probability) because it might happen that none of the jobs would have enough resources to be launched in full and those jobs would just block for the nodes to be available.

Now, care must be taken as to how the gang scheduling should be implemented - if podSets would just passively wait for all the resources to be available, that might easily lead to starvation of large jobs. On the other hand, largest gang served first would probably lead to high idling times and starvation of smaller jobs. I guess something like first-come first-served would be the good middle ground here.

I am not familiar with scheduling in Kubernetes and kube-arbitrator... Does it have a notion of a _deadline_ for a job? What I mean by that is e.g. Deployments are expected to run forever (or until downscaled/deleted), but a Job is a finite _thing_ and so maybe we could have e.g. different queues (like a 1-day queue with a runtime limit of 1 day and a week queue with runtime limit of 7 days) for different types of Jobs? That kind of thing is quite often used in large supercomputing centres and helps the scheduler make the right decision about whether to hold the nodes for a large job that is pending or whether to schedule smaller jobs instead.

I'll be digging into kube-arbitrator code today, hopefully I can come back more educated about this :)

**Comment by wojciechwasko** [comment] 2018-02-06 15:47
FWIW I got to the behaviour I more or less desired with the following patch:
```
$ git diff
diff --git a/pkg/batchd/policy/drf/drf.go b/pkg/batchd/policy/drf/drf.go
index 28126e5..348b965 100644
--- a/pkg/batchd/policy/drf/drf.go
+++ b/pkg/batchd/policy/drf/drf.go
@@ -79,13 +79,13 @@ func (drf *drfScheduler) Allocate(queues []*cache.QueueInfo, nodes []*cache.Node
                                break
                        }

-                       assigned := false
+                       //assigned := false
                        for _, node := range nodes {
                                if p.Request.LessEqual(node.Idle) {
                                        psi.assignPendingPod(node.Name)
                                        node.Idle.Sub(p.Request)

-                                       assigned = true
+                                       //assigned = true

                                        glog.V(3).Infof("assign <%v/%v> to <%s>: available <%v>, request <%v>",
                                                p.Namespace, p.Name, p.NodeName, node.Idle, p.Request)
@@ -94,9 +94,9 @@ func (drf *drfScheduler) Allocate(queues []*cache.QueueInfo, nodes []*cache.Node
                        }

                        // the left resources can not meet any pod in this podset
-                       if !assigned {
-                               break
-                       }
+                       // if !assigned {
+                       //      break
+                       // }
                }
        }
```
Simply not letting go of a `podSet` until everything is assigned.

Interestingly, I expected it to block on the `podSet` and not process anything new until that `podSet` was scheduled, but that was not the case. For my experiment, I:

1. had 3 nodes in total, 80 CPUs each
2. blocked one node with a pod requesting 50 CPUs
3. created a deployment that used kube-arbitrator with 3 replicas, minAvailable: 3, each requesting 50 CPUs
3a. _All_ the pods stayed in `Pending` instead of two pods being scheduled (GOOD!)
4. I then created another pod requesting 50 CPUs
4a. That got scheduled! Why?
5. When I deleted the two single pods blocking the nodes, the 3-pod deployment got scheduled and started Running (GOOD!)

So this "patch" would pretty much amount to "let's schedule what I can fit first", which may lead to large job starvation. But it's a start.

Q: for debugging, how can I increase the verbosity when running `kube-batchd`? I tried
```
      - command:
        - /opt/kube-batchd
        - --kubeconfig=/opt/config
        - -v=3
```
but I still see nothing in `kubectl logs kube-batchd-77fb8cfb89-vjtr9`

**Comment by wojciechwasko** [comment] 2018-02-06 16:40
Can't edit the comment from my phone but I just realized why the second single-pod job was scheduled. It wasn't governed by kube-arbitrator (it was using the default scheduler).

It'd be interesting to see if a job asking kube-arbitrator to be its scheduler would be blocked like I expected to be the case in the last comment.

**Comment by wojciechwasko** [comment] 2018-02-06 17:58
As expected, if I specify
```
  schedulerName: kube-arbitrator
```
in the second sleeper job's spec (the one which should block the node), it remains `Pending` - it's blocked by the larger, multi-node job.

**Comment by k82cn** [comment] 2018-02-07 01:03
> Interestingly, I expected it to block on the podSet and not process anything new until that podSet was scheduled, but that was not the case.

That's the case we'd like to handle in this issue :); we will block podSet until meeting `minAvailable`.

Regarding the code diff, I think it'll introduce endless loop :).

**Comment by jinzhejz** [comment] 2018-02-07 02:16
> Q: for debugging, how can I increase the verbosity when running kube-batchd?

Using `-v=3` could increase the verbosity, unfortunately, `kube-batchd` output the log to files, not to stdout/stderr, so `kubectl logs` could not get `kube-batchd` logs now.

 By default, the log file is in `/tmp` in the container. Using `--log-dir` can specify the log directory.

**Comment by wojciechwasko** [comment] 2018-02-07 07:50
@k82cn the loop will be only endless if there will never be enough resources to allocate the whole `podSet`. Otherwise, it'll break after allocating 'minAvailable'

**Comment by k82cn** [comment] 2018-02-07 11:50
@wojciechwasko, would you share your test result?

**Comment by wojciechwasko** [comment] 2018-02-07 13:00
Sure.

```
$ kubectl describe nodes | grep Allocatable -A 5
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:  8
 cpu:                             80
 memory:                          528173840Ki
 nvidia.com/gpu:                  8
 pods:                            110
--
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:  8
 cpu:                             80
 memory:                          528173840Ki
 nvidia.com/gpu:                  8
 pods:                            110
--
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:  8
 cpu:                             80
 memory:                          528173840Ki
 nvidia.com/gpu:                  8
 pods:                            110
```

Set up `kube-batchd` as usual. Set up PDBs. Create a job that will block one node.
```
$ cat pdb-min1pod.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-min1pod
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: min1pod
$ cat pdb-min3pod.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-min3pod
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: min3pod
$ kubectl create -f pdb-min1pod.yaml
poddisruptionbudget "pdb-min1pod" created
$ kubectl create -f pdb-min3pod.yaml
poddisruptionbudget "pdb-min3pod" created
$ cat wojtek-sleeper1.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wojtek-sleeper1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: min1pod
    spec:
      schedulerName: kube-arbitrator
      containers:
      - name: sleeper-pod1
        image: ubuntu
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: "50"
          requests:
            cpu: "50"
$ kubectl create -f wojtek-sleeper1.yaml
deployment "wojtek-sleeper1" created
```
Verify that it is running
```
$ kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
kube-batchd-6c94c886bb-7q4kz       1/1       Running   0          4m
wojtek-sleeper1-5668dbcd7b-7hbff   1/1       Running   0          30s
```

Create a three-node app:
```
$ cat wojtek-app.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wojtek-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: min3pod
    spec:
      schedulerName: kube-arbitrator
      containers:
      - name: mpi-pod
        image: ubuntu
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: "50"
          requests:
            cpu: "50"
$ kubectl create -f wojtek-app.yaml
deployment "wojtek-app" created
```
Verify that it is *NOT* running:
```
$ kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
kube-batchd-6c94c886bb-7q4kz       1/1       Running   0          6m
wojtek-app-7fc797c9d5-5tnn9        0/1       Pending   0          55s
wojtek-app-7fc797c9d5-gm6zl        0/1       Pending   0          55s
wojtek-app-7fc797c9d5-wx8cb        0/1       Pending   0          55s
wojtek-sleeper1-5668dbcd7b-7hbff   1/1       Running   0          2m
```
If we delete `wojtek-sleeper1`, `wojtek-app` will start running
```
$ kubectl delete -f wojtek-sleeper1.yaml
deployment "wojtek-sleeper1" deleted
$ kubectl get pods
NAME                               READY     STATUS        RESTARTS   AGE
kube-batchd-6c94c886bb-7q4kz       1/1       Running       0          14m
wojtek-app-7fc797c9d5-5tnn9        0/1       Pending       0          8m
wojtek-app-7fc797c9d5-gm6zl        0/1       Pending       0          8m
wojtek-app-7fc797c9d5-wx8cb        0/1       Pending       0          8m
wojtek-sleeper1-5668dbcd7b-7hbff   1/1       Terminating   0          9m
$ kubectl get pods
NAME                           READY     STATUS    RESTARTS   AGE
kube-batchd-6c94c886bb-7q4kz   1/1       Running   0          14m
wojtek-app-7fc797c9d5-5tnn9    1/1       Running   0          9m
wojtek-app-7fc797c9d5-gm6zl    1/1       Running   0          9m
wojtek-app-7fc797c9d5-wx8cb    1/1       Running   0          9m
```

**Comment by k82cn** [comment] 2018-02-13 02:52
xref https://github.com/kubeflow/tf-operator/issues/349

**Comment by k82cn** [comment] 2018-03-03 02:39
@wojciechwasko , would you try latest code? We did some enhancement recently :)

**Comment by k82cn** [comment] 2018-03-07 01:51
@wojciechwasko , I'm going to close this issue as related PRs were merged. If any more comments/suggestion, please feel free to open the issue :)

**Closed as completed by k82cn** 2018-03-07 01:51 UTC
Labels: area/policy, kind/feature, priority/important-soon
